services:
  app:
    build: .
    container_name: devops-start-app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: devops-start-db
    environment:
      POSTGRES_DB: devops_start
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_pass
    ports:
      - "5432:5432"